package materialize

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/suhrut/gmk/internal/ir"
)

// newTestProject constructs a Stage 2 Project with a populated RootScope.
// Stage 1's test helper built only Project.Vars; Stage 2 requires RootScope
// because resolve walks the scope chain. The aliasing of Project.Vars to
// RootScope.Vars preserves backwards compat for any reader still using
// the Stage 1 fields.
func newTestProject(t *testing.T, vars map[string]string, run string) (*ir.Project, *ir.Target) {
	t.Helper()
	root := t.TempDir()
	source := filepath.Join(root, "gmk.yml")

	rootScope := &ir.Scope{
		Path:     "/",
		Vars:     make(map[string]*ir.Var, len(vars)),
		VarOrder: make([]string, 0, len(vars)),
	}
	for k, v := range vars {
		rootScope.Vars[k] = &ir.Var{Name: k, Value: v}
		rootScope.VarOrder = append(rootScope.VarOrder, k)
	}

	p := &ir.Project{
		SourcePath: source,
		Root:       root,
		RootScope:  rootScope,
		Vars:       rootScope.Vars,     // S1 backwards-compat alias
		VarOrder:   rootScope.VarOrder, // S1 backwards-compat alias
		Targets:    make(map[string]*ir.Target),
	}

	tgt := &ir.Target{Name: "hello", Run: run, Lang: "bash", Source: ir.SourceLoc{File: source}}
	p.Targets["hello"] = tgt
	return p, tgt
}

func TestWriteScript_Basic(t *testing.T) {
	p, tgt := newTestProject(t,
		map[string]string{"name": "world"},
		`echo "hello ${name}"`,
	)

	path, err := WriteScript(tgt, p)
	if err != nil {
		t.Fatalf("WriteScript: %v", err)
	}

	wantSuffix := filepath.Join(".gmk-cache", "code", "local", "gmk.yml", "hello.sh")
	if !strings.HasSuffix(path, wantSuffix) {
		t.Errorf("path %q should end with %q", path, wantSuffix)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	content := string(data)

	if !strings.HasPrefix(content, "#!/usr/bin/env bash\n") {
		t.Errorf("script should start with bash shebang, got first line: %q", firstLine(content))
	}
	if !strings.Contains(content, "set -eo pipefail") {
		t.Error("script should contain strict mode")
	}
	if !strings.Contains(content, "Generated by gmk") {
		t.Error("script should contain generation marker")
	}
	if !strings.Contains(content, "target: hello") {
		t.Error("script header should mention target name")
	}

	if !strings.Contains(content, `echo "hello world"`) {
		t.Errorf("script body should contain resolved echo, got:\n%s", content)
	}
	if strings.Contains(content, "${name}") {
		t.Errorf("script body should not contain unresolved ${name}, got:\n%s", content)
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o755 {
		t.Errorf("perms = %v, want 0755", info.Mode().Perm())
	}
}

func TestWriteScript_NoTrailingNewline(t *testing.T) {
	p, tgt := newTestProject(t, nil, "echo hi")
	path, err := WriteScript(tgt, p)
	if err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasSuffix(string(data), "echo hi\n") {
		t.Errorf("script should end with newline; got last 20 bytes: %q", tail(string(data), 20))
	}
}

func TestWriteScript_PreservesMultilineBody(t *testing.T) {
	body := "echo line1\necho line2\necho line3"
	p, tgt := newTestProject(t, nil, body)
	path, err := WriteScript(tgt, p)
	if err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), body) {
		t.Errorf("script should preserve body lines")
	}
}

func TestWriteScript_NilTarget(t *testing.T) {
	p := &ir.Project{
		Root:       t.TempDir(),
		SourcePath: "/tmp/gmk.yml",
		RootScope:  &ir.Scope{Path: "/", Vars: make(map[string]*ir.Var)},
	}
	_, err := WriteScript(nil, p)
	if err == nil {
		t.Fatal("expected error for nil target")
	}
	if !errors.Is(err, ErrTargetNil) {
		t.Errorf("err = %v, want ErrTargetNil", err)
	}
}

func TestWriteScript_UnresolvedVarFails(t *testing.T) {
	p, tgt := newTestProject(t, nil, `echo ${missing}`)
	_, err := WriteScript(tgt, p)
	if err == nil {
		t.Fatal("expected error for undefined var")
	}
}

func TestWriteScript_OverwriteExisting(t *testing.T) {
	p, tgt := newTestProject(t, map[string]string{"v": "first"}, `echo ${v}`)

	path1, err := WriteScript(tgt, p)
	if err != nil {
		t.Fatal(err)
	}

	// Change the var via the RootScope (Stage 2 ground truth) — the alias
	// on Project.Vars points at the same map so both reads see the update.
	p.RootScope.Vars["v"].Value = "second"
	path2, err := WriteScript(tgt, p)
	if err != nil {
		t.Fatal(err)
	}

	if path1 != path2 {
		t.Errorf("path changed: %q -> %q", path1, path2)
	}

	data, err := os.ReadFile(path2)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "echo second") {
		t.Errorf("re-materialized script should contain new value, got:\n%s", data)
	}
	if strings.Contains(string(data), "echo first") {
		t.Errorf("re-materialized script should not contain old value")
	}
}

func TestAtomicWrite_NoTempFileLeft(t *testing.T) {
	dir := t.TempDir()
	target := filepath.Join(dir, "out.sh")

	if err := atomicWrite(target, []byte("content"), 0o644); err != nil {
		t.Fatal(err)
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 1 {
		names := []string{}
		for _, e := range entries {
			names = append(names, e.Name())
		}
		t.Errorf("expected 1 file, got %d: %v", len(entries), names)
	}
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}

func tail(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[len(s)-n:]
}
