// Package materialize writes a target's resolved script body to a real
// file on disk, so that exec can run it like any other shell script and
// a developer can `cat` it, `bash` it standalone, or open it in an editor.
//
// Stage 1: minimal bash header (shebang + strict mode), eager substitution
// of ${...} references into the script body, atomic file write.
//
// Stage 5 will add:
//   - Per-language headers (V= handling, error traps, PS4)
//   - Lazy-var ${LAZY_NAME} env-ref substitution (instead of literal)
//   - Generation provenance comments (source file/line, IR hash)
//   - Atomic write via temp+rename (Stage 1 already does this)
//   - Determinism guarantees (no timestamps in body)
//
// Stage 10 dispatches headers by lang. The WriteScript function signature
// and contract are stable across all stages.
package materialize

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/suhrut/gmk/internal/cache"
	"github.com/suhrut/gmk/internal/ir"
	"github.com/suhrut/gmk/internal/render"
	"github.com/suhrut/gmk/internal/resolve"
	"github.com/suhrut/gmk/internal/template"
)

// ErrTargetNil signals a programming error: WriteScript was called with
// a nil target.
var ErrTargetNil = errors.New("target is nil")

// WriteScript materializes a target's script body to a file under
// .gmk-cache/code/.../<target>.<ext> and returns the absolute path written.
//
// The file content is:
//
//	#!/usr/bin/env <interpreter>
//	# Generated by gmk — DO NOT EDIT
//	set -eo pipefail       (bash only)
//
//	<resolved run body>
//
// The function:
//
//   - Resolves ${...} references in the run body against the project's vars.
//   - Creates parent directories as needed (0755).
//   - Writes the file atomically via temp+rename within the same directory
//     so concurrent readers never see a half-written file.
//   - Marks the file executable (0755) so it can be invoked directly.
//
// Stage 5 will move the header generation into a per-language template
// system. WriteScript will then delegate to lang-specific generators.
func WriteScript(t *ir.Target, p *ir.Project) (string, error) {
	if t == nil {
		return "", ErrTargetNil
	}

	// Stage 3c: build a render dispatcher so target bodies containing
	// ${render:name(args)} are expanded before the script is written.
	// Without this, the legacy WriteScript path would fail with
	// "no render resolver configured" — leaving WriteScript out of sync
	// with the unified call/run flow in cli/run.go.
	renderDisp := render.New(p.Templates, template.Default)
	body, err := resolve.ResolveStringInScopeWithRender(t.Run, p.RootScope, renderDisp)
	if err != nil {
		return "", fmt.Errorf("materialize %s: resolve script body: %w", t.Name, err)
	}

	path := cache.ScriptPath(p.Root, p.SourcePath, t.Name, t.Lang)

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", fmt.Errorf("materialize %s: mkdir: %w", t.Name, err)
	}

	content := renderBash(t, p, body)

	if err := atomicWrite(path, []byte(content), 0o755); err != nil {
		return "", fmt.Errorf("materialize %s: write %s: %w", t.Name, path, err)
	}

	return path, nil
}

// renderBash composes the bash script content: shebang + minimal header +
// resolved body.
//
// Stage 5 replaces this with a per-language template system. The function
// is package-private so callers never see the language-specific knowledge.
func renderBash(t *ir.Target, p *ir.Project, body string) string {
	// Stage 1 deliberately keeps the header tiny so users can read the
	// whole script at a glance. Headers grow in Stage 5 to handle
	// V= verbosity, error traps, lazy-env imports, etc.
	header := fmt.Sprintf(`#!/usr/bin/env bash
# Generated by gmk from %s (target: %s)
# DO NOT EDIT — regenerated on source change
set -eo pipefail

`, p.SourcePath, t.Name)

	// Ensure the body ends with exactly one newline for clean shell parsing.
	if len(body) == 0 || body[len(body)-1] != '\n' {
		body += "\n"
	}

	return header + body
}

// atomicWrite writes data to path by first writing to a sibling temp file
// and then renaming. This guarantees readers never observe a partially-
// written file, even under concurrent gmk invocations.
//
// The temp file is created in the same directory as the target to ensure
// the rename is atomic on Unix (rename across filesystems is not).
func atomicWrite(path string, data []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	base := filepath.Base(path)

	tmp, err := os.CreateTemp(dir, "."+base+".tmp.*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()

	// Best-effort cleanup if anything below fails before the rename.
	defer func() {
		if _, statErr := os.Stat(tmpPath); statErr == nil {
			_ = os.Remove(tmpPath)
		}
	}()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}

	return os.Rename(tmpPath, path)
}
